### ISSUE TITLE
Add meta-data

### ISSUE THREAD

**Issue by boriskaus** [JuliaGeodynamics/GeophysicalModelGenerator.jl#2]
There has been a recurring request to attach metadata to the GeoData structure. In principle it should be straightforward to add another field to the GeoData structure (say a `String`). 
Yet, I am personally not really sure whether this would be sufficient or whether this needs to come in a certain form within the geosciences.

**Comment by LucaDeSiena** [comment]
What kind of metadata are we talking about? If I have an example it is easier for me to understand how to include them.

**Comment by mthielma** [comment]
We were thinking to add metadata like the one in the IRIS EMC files:
<img width="958" alt="ExMetaData" src="https://user-images.githubusercontent.com/1148509/140966581-80a20566-d217-4baa-8387-2203e6ac59b3.png">
. 
But we are happy to discuss what kind of metadata would make sense.

**Comment by mthielma** [comment]
We have now introduced an additional field "atts" in the GeoData structure. atts is a dictionary where keys and values can be given. Which attributes are set is within the responsibility of the person who is importing the data. If no attributes are given upon creation of the GeoData structure, a note will be appended that no attributes were given to this structure.

**Comment by boriskaus** [comment]
I have a number of comments:
1. Does this imply that we have to reprocess all the alps data again? That is really a pain
2. We currently have `notes` and tell that this should be a string. We could make an attributes out of that with Type `Any`. That is not type-stable but would allow to store any type of data at a later stage.

**Comment by mthielma** [comment]
We added this a while ago (Dec 7, 2021), but did not close this issue. Most of the Alps data has already been processed accordingly. 

Where is `notes` to be found? I did not find it as a filed in GeoData. Anyway, I don't think this is necessary, as `atts` has been implemented a while now. The atts dictionary also takes any data type, so I think this should be flexible enough.

**Comment by boriskaus** [comment]
Ok I see now, my mistake. My only suggestion for change would be to not print attributes if they are empty. We could make attributes `Union{Dict,Nothing}` and set the default to nothing. If nothing is set there is no need to display it; that would be a bit cleaner than the current way (and backwards compatible)

**Comment by boriskaus** [comment]
this has been implemented meanwhile
