### ISSUE TITLE
Artefacts too large

### ISSUE THREAD

**Issue by boriskaus** [JuliaGeodynamics/GeophysicalModelGenerator.jl#71]
We ran into the issue that the documentation could no longer be deployed because the bundled file was too large. I solved that by manually deleting the directory that contained `PR` in the `gh-pages` branch and by adding the `cleanup caches by a branch` workflow. yet, the [actions](https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/actions/caches) still shows that we use massive more space than we have.

@ranocha: have you seen this before perhaps?

**Comment by ranocha** [comment]
As far as I understand, these caches are the ones used in

https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/blob/15cbb45e8210137a7a9264eb40f8d5b59a90ddf5/.github/workflows/Documenter.yml#L37

and 

https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/blob/15cbb45e8210137a7a9264eb40f8d5b59a90ddf5/.github/workflows/CI.yml#L32-L41

Thus, there shouldn't be any problem if cache files are deleted - the following CI jobs will just take a bit longer. Do you have a reference to the failing documentation CI job where

> We ran into the issue that the documentation could no longer be deployed because the bundled file was too large.

happened?
