### ISSUE TITLE
Model setup tutorial

### ISSUE THREAD

**Issue by albert-de-montserrat** [JuliaGeodynamics/GeophysicalModelGenerator.jl#76]
Perhaps it would be good to have one tutorial/example of how to generate a generic model setup as in the LaMEM [example](https://github.com/JuliaGeodynamics/LaMEM.jl/blob/main/scripts/Subduction3D.jl), but without all the LaMEM specific functions.

**Comment by boriskaus** [comment]
Yes we have planned one for the JOSS paper

**Comment by boriskaus** [comment]
added in PR#92
