### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by albert-de-montserrat** [JuliaGeodynamics/GeophysicalModelGenerator.jl#77]
Typically functions names start with lower case letter while `struct`s names start with upper case. I find it quite confusing that in GMG both functions and `struct`s start with upper case.  I know this is a large and highly breaking change, but it would be good to eventually / slowly move to the upper/lower case name convention.

**Comment by boriskaus** [comment]
Uff, I somehow missed that. That is indeed a huge amount of work

**Comment by boriskaus** [comment]
fixed in PR#99
