### ISSUE TITLE
Importing Screenshots in UTM Coordinates

### ISSUE THREAD

**Issue by ew-beep** [JuliaGeodynamics/GeophysicalModelGenerator.jl#8]
With the functions 
```julia
GeophysicalModelGenerator.Screenshot_To_GeoData
```
and 
```julia
GeophysicalModelGenerator.Screenshot_To_CartData
```
screenshots can be imported as GeoData and CartData as described in the [tutorial](https://juliageodynamics.github.io/GeophysicalModelGenerator.jl/dev/man/tutorial_Screenshot_To_Paraview/). It would be helpful if there was a function that does the same for UTMData.

**Comment by boriskaus** [comment]
good idea. 
Please note that I just got rid of the `CartData` structure, as we really meant "cartesian data that can produce output that Paraview likes" with that structure. `CartData` was therefore renamed to `ParaviewData`. Should be there in version 0.3.6.
At some stage I will reintroduce a `CartData`, aka true cartesian data structure, which has `x,y,z` coordinates, of the type that LaMEM produces.

**Comment by boriskaus** [comment]
This was added in v0.3.10
